#!/usr/bin/python3

from importlib.metadata import requires
import click
from svl2.core import Prime

@click.command()
@click.option('-r','--html_path',required=True,help="极光漏扫报告html文件夹路径")
@click.option('-x','--xlsx_path',default='',help='漏扫目标信息的excel表路径，表头必须包含ip和name字段')
@click.option('-o','--output_path',default='./out.docx',help='word格式报告输出全路径')
def core(html_path, xlsx_path, output_path):
  prime = Prime()
  prime.set_html_path(html_path)
  prime.set_xlsx_path(xlsx_path)
  prime.set_output_full_path(output_path)
  prime.run()

if __name__ == "__main__":
  core()